#!/bin/bash

cppcheck \
    --error-exitcode=1 \
    --enable=style \
    --enable=performance \
    --enable=portability \
    --suppress=unusedFunctions \
    --suppress=toomanyconfigs \
    atc.c {tree,fileio,basefile_processor}.{c,h}
