name: build opensource COBOL 4J

on:
  push:
  pull_request:
    types: [opened, reopened, review_requested, synchronize]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 

      - uses: actions/checkout@v4

      - name: Install static analysis tools
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang-format cppcheck

      - name: Build
        run: |
          make
      
      - name: Check formatting
        working-directory: src
        run: |
          ./check-format

      - name: cppcheck
        working-directory: src
        run: |
          ./cppcheck

      - name: Test
        run: |
          make test